### ISSUE TITLE
Can't see text in posts

### ISSUE THREAD

**Issue by theboomr** [zachatrocity/lemmynade#11]
### Device info

- OS: Android
- OS version: 13
- Device: Galaxy S23
- Lemmynade version: 0.9.5

### Describe the bug

When opening any post that has some text in it, I cannot see the text at all, just the image/link, and the comments below. If I tap on the reply button, then I do see the text contents of the post in the reply window.

### Expected behavior

I expect to see the post text content after tapping on the post. 

### Screenshots/Screencasts

Attached screenshots of post with no text showing, and then the reply screen where the text does show.

![Screenshot_20230622_144533.png](https://github.com/zachatrocity/lemmynade/assets/12604903/4c270ff3-c549-4fdc-92b9-0b5001f6a1d0)

![Screenshot_20230622_144539.png](https://github.com/zachatrocity/lemmynade/assets/12604903/5da7a6c2-eef9-4aa7-8814-12fb23b0dc9b)

**Comment by zachatrocity** [comment]
Oops. Yeah I'll fix this asap.

If you disable compact mode I suspect it will work again

**Comment by theboomr** [comment]
Ooh, yep that does fix it! Thanks for the workaround. Really liking the app so far!
