### ISSUE TITLE
Lemmynade can't find some instances (Lemmur Problem)

### ISSUE THREAD

**Issue by turradeira** [zachatrocity/lemmynade#12]
### Device info

- OS: Android
- OS version: MIUI 13.0.9
- Device: Redmi Note 10S
- Lemmynade version: 0.9.5

### Describe the bug

Some instances of Lemmy can't be found, even though they exist.
I use a Portuguese instance (lemmy.pt) and can't log in due to Lemmynade (and Lemmur since it has the exact same problem) not being able to find them

### Steps to reproduce

1. Go to the 'Account' Menu
2. Click on 'Add account'
3. Click on 'Add account' (again)
4. 'Select instance'
5. 'Add instance'
6. in instance URL input the instance URL (in my case lemmy.pt)
7. 'Add'
8. "Instance can't be found"

### Screenshots/Screencasts
![photo_2023-06-22_23-05-59](https://github.com/zachatrocity/lemmynade/assets/36634189/0f44ac65-8ad7-4aad-8bdc-839ecc44fd4d)

**Comment by zachatrocity** [comment]
this is due to breaking changes in the api for v0.18.x will work on a fix

**Comment by zachatrocity** [comment]
@turradeira this is fixed in 

https://github.com/zachatrocity/lemmynade/releases/tag/v0.9.6

**Comment by turradeira** [comment]
@zachatrocity thanks mate
