### ISSUE TITLE
Comments don't work outside of own instance

### ISSUE THREAD

**Issue by NicoCharrua** [zachatrocity/lemmynade#7]
### Device info

- OS: Android
- OS version: 13 (TQ3A.230605.010)
- Device: Pixel 6A
- Lemmynade version: 0.9.4

### Describe the bug

Comments don't load outside of my home instance. My home instance is Lemmy.ca, and all posts I checked on there load fine. All posts I checked on other instances showed "*no comments yet*".

### Steps to reproduce

1. Go to any post posted outside of your home instance
2. Scroll down to the comments
3. See error

### Relevant logs

The logs page just says "*no logs*"

### Expected behavior

The comments load

### Screenshots/Screencasts

![Screenshot_20230622-122419](https://github.com/zachatrocity/lemmynade/assets/55714525/f7fbdc81-22b6-4d36-9bdb-4d45fe2ab0ae)
![Screenshot_20230622-122456](https://github.com/zachatrocity/lemmynade/assets/55714525/0c36e32c-3dfa-46c1-835e-0e9f3848ba08)

### Additional context

Just wanted to say that this app is looking great! I'm glad to see more third party apps for Lemmy being worked on.

Got the app from [here](https://github.com/zachatrocity/lemmynade/actions/runs/5341509186) since the releases only show the source code.

Saw this:   

>There is a significant bug with the comments not working properly. They’re not nested under the parent comments.

But I think that's a different issue

**Comment by zachatrocity** [comment]
Thanks for reporting! I believe this is fixed in #6 :

![image](https://github.com/zachatrocity/lemmynade/assets/6200670/1adfb263-5fda-4f0c-a7f8-31ef230729f7)

**Comment by zachatrocity** [comment]
Fixed in PR #8 !

@NicoCharrua  Going to close, let me know if you still see issues. Will push a new release in an hour, gonna get the compact card view in first.

**Comment by NicoCharrua** [comment]
@zachatrocity it works now in 0.9.6, thanks!
